# Generated by Django 5.0.7 on 2024-07-26 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(default=datetime.datetime(2024, 7, 26, 13, 4, 29, 317273))),
            ],
        ),
    ]
