# Generated by Django 5.0.7 on 2024-07-29 07:54

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('SelectCategory', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Uploadfile', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('ExpertiseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ExpertiseName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField(default=datetime.datetime.now)),
                ('JobType', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Experience', models.CharField(max_length=50)),
                ('WorkingHours', models.CharField(max_length=100)),
                ('WorkingDays', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Vacancy', models.IntegerField(default='')),
                ('DeadLine', models.CharField(max_length=50)),
                ('Sluglink', models.SlugField(null=True, unique=True)),
                ('Active_status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 13, 24, 43, 113843)),
        ),
    ]
