# Generated by Django 5.0.7 on 2024-07-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stepformdata_alter_contactdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 17, 34, 32, 991935)),
        ),
    ]
