# Generated by Django 5.0.7 on 2024-08-12 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_contactdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepformdata',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='stepformdata',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stepformdata',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 14, 45, 10, 697480)),
        ),
    ]
