# Generated by Django 5.0.7 on 2024-12-03 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_email_stepformdata_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntalksForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intalk_Name', models.CharField(max_length=100)),
                ('Intalk_Email', models.EmailField(max_length=50)),
                ('Intalk_Contact', models.CharField(max_length=10)),
                ('Intalk_City', models.CharField(max_length=10)),
                ('Intalk_Reason_to_connect', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 11, 5, 42, 627887)),
        ),
    ]
