# Generated by Django 5.2.3 on 2025-10-22 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_intalk_city_intalksform_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('q1_answer', models.TextField(blank=True, null=True)),
                ('q2_answer', models.TextField(blank=True, null=True)),
                ('q3_answer', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 7, 30, 51, 200056)),
        ),
    ]
